SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

BLOCK_SIZE = 40

DEFAULT_DELAY = 600
MINIMUM_DELAY = 200

SPEED_UP = 40

DIFFICULTY_THRESHOLD = 5

SAVES = "scores.json"

FONT_SIZE = SCREEN_HEIGHT // 22
LINE_OFFSET = SCREEN_HEIGHT // 20